# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\renlianshibie\test_01.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("MainWindow")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(64, 142, 1318, 777))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 37,1);\n"
"border-top-left-radius:150px;\n"
"border-top-right-radius:150px;\n"
"border-bottom-left-radius:50px;\n"
"border-bottom-right-radius:150px;\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_video_rect_bg = QtWidgets.QLabel(self.centralWidget)
        self.label_video_rect_bg.setGeometry(QtCore.QRect(60, 128, 1328, 798))
        self.label_video_rect_bg.setStyleSheet("background-color: rgba(255, 170, 0, 0);")
        self.label_video_rect_bg.setText("")
        self.label_video_rect_bg.setObjectName("label_video_rect_bg")
        self.label_userinfo_all_bg = QtWidgets.QLabel(self.centralWidget)
        self.label_userinfo_all_bg.setGeometry(QtCore.QRect(1098, 430, 242, 389))
        self.label_userinfo_all_bg.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_userinfo_all_bg.setText("")
        self.label_userinfo_all_bg.setObjectName("label_userinfo_all_bg")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1110, 440, 221, 371))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_user_maininfo = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_user_maininfo.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_user_maininfo.setObjectName("verticalLayout_user_maininfo")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(126, 150))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_2.setBaseSize(QtCore.QSize(8, 0))
        self.label_2.setToolTip("")
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_user_maininfo.addWidget(self.label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_userinfo_all_name = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_userinfo_all_name.setStyleSheet("font: 14pt \"华文宋体\";\n"
"color:#fff;")
        self.label_userinfo_all_name.setObjectName("label_userinfo_all_name")
        self.verticalLayout_3.addWidget(self.label_userinfo_all_name)
        self.label_userinfo_all_sex = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_userinfo_all_sex.setStyleSheet("font: 14pt \"华文宋体\";\n"
"color:#fff;")
        self.label_userinfo_all_sex.setObjectName("label_userinfo_all_sex")
        self.verticalLayout_3.addWidget(self.label_userinfo_all_sex)
        self.label_userinfo_all_age = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_userinfo_all_age.setStyleSheet("font: 14pt \"华文宋体\";\n"
"color:#fff;")
        self.label_userinfo_all_age.setObjectName("label_userinfo_all_age")
        self.verticalLayout_3.addWidget(self.label_userinfo_all_age)
        self.label_userinfo_all_rank = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_userinfo_all_rank.setStyleSheet("font: 14pt \"华文宋体\";\n"
"color:#fff;")
        self.label_userinfo_all_rank.setObjectName("label_userinfo_all_rank")
        self.verticalLayout_3.addWidget(self.label_userinfo_all_rank)
        self.label_userinfo_all_dept = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_userinfo_all_dept.setStyleSheet("font: 14pt \"华文宋体\";\n"
"color:#fff;")
        self.label_userinfo_all_dept.setObjectName("label_userinfo_all_dept")
        self.verticalLayout_3.addWidget(self.label_userinfo_all_dept)
        self.label_userinfo_all_slogan = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_userinfo_all_slogan.setStyleSheet("font: 14pt \"华文宋体\";\n"
"color:#fff;")
        self.label_userinfo_all_slogan.setObjectName("label_userinfo_all_slogan")
        self.verticalLayout_3.addWidget(self.label_userinfo_all_slogan)
        self.verticalLayout_user_maininfo.addLayout(self.verticalLayout_3)
        self.label_right_top_time = QtWidgets.QLabel(self.centralWidget)
        self.label_right_top_time.setGeometry(QtCore.QRect(1430, 20, 121, 40))
        self.label_right_top_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_right_top_time.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"color:#fff;")
        self.label_right_top_time.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_right_top_time.setObjectName("label_right_top_time")
        self.label_right_top_date = QtWidgets.QLabel(self.centralWidget)
        self.label_right_top_date.setGeometry(QtCore.QRect(1300, 30, 131, 21))
        self.label_right_top_date.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color:#24b7e7;")
        self.label_right_top_date.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_right_top_date.setObjectName("label_right_top_date")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(1473, 198, 341, 85))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_list_0 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_list_0.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list_0.setHorizontalSpacing(6)
        self.gridLayout_list_0.setObjectName("gridLayout_list_0")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(14, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_list_0.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_list_0.addWidget(self.label_11, 1, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_user_list_time_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_user_list_time_0.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_time_0.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_time_0.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_time_0.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_time_0.setObjectName("label_user_list_time_0")
        self.verticalLayout_6.addWidget(self.label_user_list_time_0)
        self.label_user_list_date_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_user_list_date_0.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_date_0.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_date_0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_date_0.setObjectName("label_user_list_date_0")
        self.verticalLayout_6.addWidget(self.label_user_list_date_0)
        self.gridLayout_list_0.addLayout(self.verticalLayout_6, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 9))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 9))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_list_0.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_list_avatar_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_list_avatar_0.setMinimumSize(QtCore.QSize(55, 55))
        self.label_list_avatar_0.setMaximumSize(QtCore.QSize(50, 55))
        self.label_list_avatar_0.setToolTipDuration(0)
        self.label_list_avatar_0.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_list_avatar_0.setLineWidth(0)
        self.label_list_avatar_0.setText("")
        self.label_list_avatar_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_avatar_0.setIndent(0)
        self.label_list_avatar_0.setObjectName("label_list_avatar_0")
        self.gridLayout_list_0.addWidget(self.label_list_avatar_0, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 7))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 7))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_list_0.addWidget(self.label_4, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_user_list_name_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_user_list_name_0.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_name_0.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_name_0.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_name_0.setObjectName("label_user_list_name_0")
        self.verticalLayout.addWidget(self.label_user_list_name_0)
        self.label_user_list_dept_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_user_list_dept_0.setMinimumSize(QtCore.QSize(123, 0))
        self.label_user_list_dept_0.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_dept_0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_dept_0.setObjectName("label_user_list_dept_0")
        self.verticalLayout.addWidget(self.label_user_list_dept_0)
        self.gridLayout_list_0.addLayout(self.verticalLayout, 1, 3, 1, 1)
        self.label_list_bg_0 = QtWidgets.QLabel(self.centralWidget)
        self.label_list_bg_0.setGeometry(QtCore.QRect(1476, 198, 334, 85))
        self.label_list_bg_0.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_list_bg_0.setText("")
        self.label_list_bg_0.setObjectName("label_list_bg_0")
        self.label_user_list_head_rect_0 = QtWidgets.QLabel(self.centralWidget)
        self.label_user_list_head_rect_0.setGeometry(QtCore.QRect(1491, 209, 60, 60))
        self.label_user_list_head_rect_0.setStyleSheet("background-color: rgba(255, 170, 0, 0.5);")
        self.label_user_list_head_rect_0.setText("")
        self.label_user_list_head_rect_0.setObjectName("label_user_list_head_rect_0")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(1473, 293, 341, 85))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_list_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_list_1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list_1.setHorizontalSpacing(6)
        self.gridLayout_list_1.setObjectName("gridLayout_list_1")
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.gridLayout_list_1.addWidget(self.label_22, 1, 2, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_user_list_time_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_list_time_1.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_time_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_time_1.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_time_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_time_1.setObjectName("label_user_list_time_1")
        self.verticalLayout_8.addWidget(self.label_user_list_time_1)
        self.label_user_list_date_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_list_date_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_date_1.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_date_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_date_1.setObjectName("label_user_list_date_1")
        self.verticalLayout_8.addWidget(self.label_user_list_date_1)
        self.gridLayout_list_1.addLayout(self.verticalLayout_8, 1, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setMinimumSize(QtCore.QSize(0, 9))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 9))
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.gridLayout_list_1.addWidget(self.label_25, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_27.setMinimumSize(QtCore.QSize(0, 7))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 7))
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_list_1.addWidget(self.label_27, 0, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_user_list_name_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_list_name_1.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_name_1.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_name_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_name_1.setObjectName("label_user_list_name_1")
        self.verticalLayout_9.addWidget(self.label_user_list_name_1)
        self.label_user_list_dept_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_list_dept_1.setMinimumSize(QtCore.QSize(123, 0))
        self.label_user_list_dept_1.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_dept_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_dept_1.setObjectName("label_user_list_dept_1")
        self.verticalLayout_9.addWidget(self.label_user_list_dept_1)
        self.gridLayout_list_1.addLayout(self.verticalLayout_9, 1, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setMaximumSize(QtCore.QSize(14, 16777215))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.gridLayout_list_1.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_list_avatar_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_list_avatar_1.setMinimumSize(QtCore.QSize(55, 55))
        self.label_list_avatar_1.setMaximumSize(QtCore.QSize(50, 55))
        self.label_list_avatar_1.setToolTipDuration(0)
        self.label_list_avatar_1.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_list_avatar_1.setLineWidth(0)
        self.label_list_avatar_1.setText("")
        self.label_list_avatar_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_avatar_1.setIndent(0)
        self.label_list_avatar_1.setObjectName("label_list_avatar_1")
        self.gridLayout_list_1.addWidget(self.label_list_avatar_1, 1, 1, 1, 1)
        self.label_list_avatar_1.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_25.raise_()
        self.label_27.raise_()
        self.label_user_list_head_rect_1 = QtWidgets.QLabel(self.centralWidget)
        self.label_user_list_head_rect_1.setGeometry(QtCore.QRect(1490, 304, 60, 60))
        self.label_user_list_head_rect_1.setStyleSheet("background-color: rgba(255, 170, 0, 0.5);")
        self.label_user_list_head_rect_1.setText("")
        self.label_user_list_head_rect_1.setObjectName("label_user_list_head_rect_1")
        self.label_list_bg_1 = QtWidgets.QLabel(self.centralWidget)
        self.label_list_bg_1.setGeometry(QtCore.QRect(1476, 293, 334, 85))
        self.label_list_bg_1.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_list_bg_1.setText("")
        self.label_list_bg_1.setObjectName("label_list_bg_1")
        self.label_user_list_head_rect_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_user_list_head_rect_2.setGeometry(QtCore.QRect(1490, 400, 60, 60))
        self.label_user_list_head_rect_2.setStyleSheet("background-color: rgba(255, 170, 0, 0.5);")
        self.label_user_list_head_rect_2.setText("")
        self.label_user_list_head_rect_2.setObjectName("label_user_list_head_rect_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(1472, 389, 341, 85))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_list_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_list_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list_2.setHorizontalSpacing(6)
        self.gridLayout_list_2.setObjectName("gridLayout_list_2")
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_30.setMaximumSize(QtCore.QSize(14, 16777215))
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_list_2.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_31.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.gridLayout_list_2.addWidget(self.label_31, 1, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_user_list_time_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_user_list_time_2.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_time_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_time_2.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_time_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_time_2.setObjectName("label_user_list_time_2")
        self.verticalLayout_10.addWidget(self.label_user_list_time_2)
        self.label_user_list_date_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_user_list_date_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_date_2.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_date_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_date_2.setObjectName("label_user_list_date_2")
        self.verticalLayout_10.addWidget(self.label_user_list_date_2)
        self.gridLayout_list_2.addLayout(self.verticalLayout_10, 1, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_34.setMinimumSize(QtCore.QSize(0, 9))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 9))
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.gridLayout_list_2.addWidget(self.label_34, 2, 1, 1, 1)
        self.label_list_avatar_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_list_avatar_2.setMinimumSize(QtCore.QSize(55, 55))
        self.label_list_avatar_2.setMaximumSize(QtCore.QSize(50, 55))
        self.label_list_avatar_2.setToolTipDuration(0)
        self.label_list_avatar_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_list_avatar_2.setLineWidth(0)
        self.label_list_avatar_2.setText("")
        self.label_list_avatar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_avatar_2.setIndent(0)
        self.label_list_avatar_2.setObjectName("label_list_avatar_2")
        self.gridLayout_list_2.addWidget(self.label_list_avatar_2, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_36.setMinimumSize(QtCore.QSize(0, 7))
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 7))
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.gridLayout_list_2.addWidget(self.label_36, 0, 1, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_user_list_name_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_user_list_name_2.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_name_2.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_name_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_name_2.setObjectName("label_user_list_name_2")
        self.verticalLayout_11.addWidget(self.label_user_list_name_2)
        self.label_user_list_dept_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_user_list_dept_2.setMinimumSize(QtCore.QSize(123, 0))
        self.label_user_list_dept_2.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_dept_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_dept_2.setObjectName("label_user_list_dept_2")
        self.verticalLayout_11.addWidget(self.label_user_list_dept_2)
        self.gridLayout_list_2.addLayout(self.verticalLayout_11, 1, 3, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(1472, 484, 341, 85))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_list_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_list_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list_3.setHorizontalSpacing(6)
        self.gridLayout_list_3.setObjectName("gridLayout_list_3")
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_39.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout_list_3.addWidget(self.label_39, 1, 2, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_user_list_time_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_user_list_time_3.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_time_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_time_3.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_time_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_time_3.setObjectName("label_user_list_time_3")
        self.verticalLayout_12.addWidget(self.label_user_list_time_3)
        self.label_user_list_date_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_user_list_date_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_date_3.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_date_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_date_3.setObjectName("label_user_list_date_3")
        self.verticalLayout_12.addWidget(self.label_user_list_date_3)
        self.gridLayout_list_3.addLayout(self.verticalLayout_12, 1, 4, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_42.setMinimumSize(QtCore.QSize(0, 9))
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 9))
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.gridLayout_list_3.addWidget(self.label_42, 2, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_43.setMinimumSize(QtCore.QSize(0, 7))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 7))
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.gridLayout_list_3.addWidget(self.label_43, 0, 1, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_user_list_name_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_user_list_name_3.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_name_3.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_name_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_name_3.setObjectName("label_user_list_name_3")
        self.verticalLayout_13.addWidget(self.label_user_list_name_3)
        self.label_user_list_dept_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_user_list_dept_3.setMinimumSize(QtCore.QSize(123, 0))
        self.label_user_list_dept_3.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_dept_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_dept_3.setObjectName("label_user_list_dept_3")
        self.verticalLayout_13.addWidget(self.label_user_list_dept_3)
        self.gridLayout_list_3.addLayout(self.verticalLayout_13, 1, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_46.setMaximumSize(QtCore.QSize(14, 16777215))
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.gridLayout_list_3.addWidget(self.label_46, 1, 0, 1, 1)
        self.label_list_avatar_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_list_avatar_3.setMinimumSize(QtCore.QSize(55, 55))
        self.label_list_avatar_3.setMaximumSize(QtCore.QSize(50, 55))
        self.label_list_avatar_3.setToolTipDuration(0)
        self.label_list_avatar_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_list_avatar_3.setLineWidth(0)
        self.label_list_avatar_3.setText("")
        self.label_list_avatar_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_avatar_3.setIndent(0)
        self.label_list_avatar_3.setObjectName("label_list_avatar_3")
        self.gridLayout_list_3.addWidget(self.label_list_avatar_3, 1, 1, 1, 1)
        self.label_list_bg_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_list_bg_2.setGeometry(QtCore.QRect(1476, 389, 334, 85))
        self.label_list_bg_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_list_bg_2.setText("")
        self.label_list_bg_2.setObjectName("label_list_bg_2")
        self.label_user_list_head_rect_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_user_list_head_rect_3.setGeometry(QtCore.QRect(1490, 495, 60, 60))
        self.label_user_list_head_rect_3.setStyleSheet("background-color: rgba(255, 170, 0, 0.5);")
        self.label_user_list_head_rect_3.setText("")
        self.label_user_list_head_rect_3.setObjectName("label_user_list_head_rect_3")
        self.label_list_bg_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_list_bg_3.setGeometry(QtCore.QRect(1476, 485, 334, 85))
        self.label_list_bg_3.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_list_bg_3.setText("")
        self.label_list_bg_3.setObjectName("label_list_bg_3")
        self.label_user_list_head_rect_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_user_list_head_rect_6.setGeometry(QtCore.QRect(1491, 781, 60, 60))
        self.label_user_list_head_rect_6.setStyleSheet("background-color: rgba(255, 170, 0, 0.5);")
        self.label_user_list_head_rect_6.setText("")
        self.label_user_list_head_rect_6.setObjectName("label_user_list_head_rect_6")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(1472, 674, 341, 85))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_list_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_list_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list_5.setHorizontalSpacing(6)
        self.gridLayout_list_5.setObjectName("gridLayout_list_5")
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_48.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.gridLayout_list_5.addWidget(self.label_48, 1, 2, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_user_list_time_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_list_time_5.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_time_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_time_5.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_time_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_time_5.setObjectName("label_user_list_time_5")
        self.verticalLayout_14.addWidget(self.label_user_list_time_5)
        self.label_user_list_date_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_list_date_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_date_5.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_date_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_date_5.setObjectName("label_user_list_date_5")
        self.verticalLayout_14.addWidget(self.label_user_list_date_5)
        self.gridLayout_list_5.addLayout(self.verticalLayout_14, 1, 4, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_51.setMinimumSize(QtCore.QSize(0, 9))
        self.label_51.setMaximumSize(QtCore.QSize(16777215, 9))
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.gridLayout_list_5.addWidget(self.label_51, 2, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_52.setMinimumSize(QtCore.QSize(0, 7))
        self.label_52.setMaximumSize(QtCore.QSize(16777215, 7))
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.gridLayout_list_5.addWidget(self.label_52, 0, 1, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_user_list_name_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_list_name_5.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_name_5.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_name_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_name_5.setObjectName("label_user_list_name_5")
        self.verticalLayout_15.addWidget(self.label_user_list_name_5)
        self.label_user_list_dept_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_list_dept_5.setMinimumSize(QtCore.QSize(123, 0))
        self.label_user_list_dept_5.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_dept_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_dept_5.setObjectName("label_user_list_dept_5")
        self.verticalLayout_15.addWidget(self.label_user_list_dept_5)
        self.gridLayout_list_5.addLayout(self.verticalLayout_15, 1, 3, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_55.setMaximumSize(QtCore.QSize(14, 16777215))
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.gridLayout_list_5.addWidget(self.label_55, 1, 0, 1, 1)
        self.label_list_avatar_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_list_avatar_5.setMinimumSize(QtCore.QSize(55, 55))
        self.label_list_avatar_5.setMaximumSize(QtCore.QSize(50, 55))
        self.label_list_avatar_5.setToolTipDuration(0)
        self.label_list_avatar_5.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_list_avatar_5.setLineWidth(0)
        self.label_list_avatar_5.setText("")
        self.label_list_avatar_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_avatar_5.setIndent(0)
        self.label_list_avatar_5.setObjectName("label_list_avatar_5")
        self.gridLayout_list_5.addWidget(self.label_list_avatar_5, 1, 1, 1, 1)
        self.label_list_bg_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_list_bg_5.setGeometry(QtCore.QRect(1475, 674, 334, 85))
        self.label_list_bg_5.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_list_bg_5.setText("")
        self.label_list_bg_5.setObjectName("label_list_bg_5")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(1473, 770, 341, 85))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_list_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_list_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list_6.setHorizontalSpacing(6)
        self.gridLayout_list_6.setObjectName("gridLayout_list_6")
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_57.setMaximumSize(QtCore.QSize(14, 16777215))
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.gridLayout_list_6.addWidget(self.label_57, 1, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_58.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.gridLayout_list_6.addWidget(self.label_58, 1, 2, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_user_list_time_6 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_user_list_time_6.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_time_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_time_6.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_time_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_time_6.setObjectName("label_user_list_time_6")
        self.verticalLayout_16.addWidget(self.label_user_list_time_6)
        self.label_user_list_date_6 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_user_list_date_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_date_6.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_date_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_date_6.setObjectName("label_user_list_date_6")
        self.verticalLayout_16.addWidget(self.label_user_list_date_6)
        self.gridLayout_list_6.addLayout(self.verticalLayout_16, 1, 4, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_61.setMinimumSize(QtCore.QSize(0, 9))
        self.label_61.setMaximumSize(QtCore.QSize(16777215, 9))
        self.label_61.setText("")
        self.label_61.setObjectName("label_61")
        self.gridLayout_list_6.addWidget(self.label_61, 2, 1, 1, 1)
        self.label_list_avatar_6 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_list_avatar_6.setMinimumSize(QtCore.QSize(55, 55))
        self.label_list_avatar_6.setMaximumSize(QtCore.QSize(50, 55))
        self.label_list_avatar_6.setToolTipDuration(0)
        self.label_list_avatar_6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_list_avatar_6.setLineWidth(0)
        self.label_list_avatar_6.setText("")
        self.label_list_avatar_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_avatar_6.setIndent(0)
        self.label_list_avatar_6.setObjectName("label_list_avatar_6")
        self.gridLayout_list_6.addWidget(self.label_list_avatar_6, 1, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_63.setMinimumSize(QtCore.QSize(0, 7))
        self.label_63.setMaximumSize(QtCore.QSize(16777215, 7))
        self.label_63.setText("")
        self.label_63.setObjectName("label_63")
        self.gridLayout_list_6.addWidget(self.label_63, 0, 1, 1, 1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_user_list_name_6 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_user_list_name_6.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_name_6.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_name_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_name_6.setObjectName("label_user_list_name_6")
        self.verticalLayout_17.addWidget(self.label_user_list_name_6)
        self.label_user_list_dept_6 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_user_list_dept_6.setMinimumSize(QtCore.QSize(123, 0))
        self.label_user_list_dept_6.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_dept_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_dept_6.setObjectName("label_user_list_dept_6")
        self.verticalLayout_17.addWidget(self.label_user_list_dept_6)
        self.gridLayout_list_6.addLayout(self.verticalLayout_17, 1, 3, 1, 1)
        self.label_user_list_head_rect_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_user_list_head_rect_4.setGeometry(QtCore.QRect(1490, 590, 60, 60))
        self.label_user_list_head_rect_4.setStyleSheet("background-color: rgba(255, 170, 0, 0.5);")
        self.label_user_list_head_rect_4.setText("")
        self.label_user_list_head_rect_4.setObjectName("label_user_list_head_rect_4")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(1472, 579, 341, 85))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_list_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_list_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list_4.setHorizontalSpacing(6)
        self.gridLayout_list_4.setObjectName("gridLayout_list_4")
        self.label_75 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_75.setMaximumSize(QtCore.QSize(14, 16777215))
        self.label_75.setText("")
        self.label_75.setObjectName("label_75")
        self.gridLayout_list_4.addWidget(self.label_75, 1, 0, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_76.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_76.setText("")
        self.label_76.setObjectName("label_76")
        self.gridLayout_list_4.addWidget(self.label_76, 1, 2, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_user_list_time_4 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_user_list_time_4.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_time_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_time_4.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_time_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_time_4.setObjectName("label_user_list_time_4")
        self.verticalLayout_20.addWidget(self.label_user_list_time_4)
        self.label_user_list_date_4 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_user_list_date_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_user_list_date_4.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_date_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_date_4.setObjectName("label_user_list_date_4")
        self.verticalLayout_20.addWidget(self.label_user_list_date_4)
        self.gridLayout_list_4.addLayout(self.verticalLayout_20, 1, 4, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_79.setMinimumSize(QtCore.QSize(0, 9))
        self.label_79.setMaximumSize(QtCore.QSize(16777215, 9))
        self.label_79.setText("")
        self.label_79.setObjectName("label_79")
        self.gridLayout_list_4.addWidget(self.label_79, 2, 1, 1, 1)
        self.label_list_avatar_4 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_list_avatar_4.setMinimumSize(QtCore.QSize(55, 55))
        self.label_list_avatar_4.setMaximumSize(QtCore.QSize(50, 55))
        self.label_list_avatar_4.setToolTipDuration(0)
        self.label_list_avatar_4.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_list_avatar_4.setLineWidth(0)
        self.label_list_avatar_4.setText("")
        self.label_list_avatar_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_avatar_4.setIndent(0)
        self.label_list_avatar_4.setObjectName("label_list_avatar_4")
        self.gridLayout_list_4.addWidget(self.label_list_avatar_4, 1, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_81.setMinimumSize(QtCore.QSize(0, 7))
        self.label_81.setMaximumSize(QtCore.QSize(16777215, 7))
        self.label_81.setText("")
        self.label_81.setObjectName("label_81")
        self.gridLayout_list_4.addWidget(self.label_81, 0, 1, 1, 1)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_user_list_name_4 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_user_list_name_4.setMinimumSize(QtCore.QSize(0, 27))
        self.label_user_list_name_4.setStyleSheet("font: 13pt \"宋体\";\n"
"color:#fff;")
        self.label_user_list_name_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_user_list_name_4.setObjectName("label_user_list_name_4")
        self.verticalLayout_21.addWidget(self.label_user_list_name_4)
        self.label_user_list_dept_4 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_user_list_dept_4.setMinimumSize(QtCore.QSize(123, 0))
        self.label_user_list_dept_4.setStyleSheet("color:#24b7e7;\n"
"font: 10pt \"宋体\";")
        self.label_user_list_dept_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_list_dept_4.setObjectName("label_user_list_dept_4")
        self.verticalLayout_21.addWidget(self.label_user_list_dept_4)
        self.gridLayout_list_4.addLayout(self.verticalLayout_21, 1, 3, 1, 1)
        self.label_user_list_head_rect_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_user_list_head_rect_5.setGeometry(QtCore.QRect(1490, 685, 60, 60))
        self.label_user_list_head_rect_5.setStyleSheet("background-color: rgba(255, 170, 0, 0.5);")
        self.label_user_list_head_rect_5.setText("")
        self.label_user_list_head_rect_5.setObjectName("label_user_list_head_rect_5")
        self.label_list_bg_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_list_bg_4.setGeometry(QtCore.QRect(1476, 579, 334, 85))
        self.label_list_bg_4.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_list_bg_4.setText("")
        self.label_list_bg_4.setObjectName("label_list_bg_4")
        self.label_list_bg_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_list_bg_6.setGeometry(QtCore.QRect(1476, 770, 334, 85))
        self.label_list_bg_6.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_list_bg_6.setText("")
        self.label_list_bg_6.setObjectName("label_list_bg_6")
        self.label_notice = QtWidgets.QLabel(self.centralWidget)
        self.label_notice.setGeometry(QtCore.QRect(111, 856, 1191, 31))
        self.label_notice.setStyleSheet("font: 16pt \"华文琥珀\";\n"
"color:#FFF;")
        self.label_notice.setObjectName("label_notice")
        self.user_list_right_wraper = QtWidgets.QLabel(self.centralWidget)
        self.user_list_right_wraper.setGeometry(QtCore.QRect(1422, 131, 439, 794))
        self.user_list_right_wraper.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.user_list_right_wraper.setText("")
        self.user_list_right_wraper.setObjectName("user_list_right_wraper")
        self.label_shadow_tips = QtWidgets.QLabel(self.centralWidget)
        self.label_shadow_tips.setGeometry(QtCore.QRect(70, 450, 1301, 191))
        self.label_shadow_tips.setStyleSheet("background-color: rgba(0, 0, 37,0.5);\n"
"color:#FFF;\n"
"font: 75 36pt \"Agency FB\";")
        self.label_shadow_tips.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shadow_tips.setObjectName("label_shadow_tips")
        self.label_3.raise_()
        self.label_shadow_tips.raise_()
        self.label_video_rect_bg.raise_()
        self.label_list_bg_6.raise_()
        self.label_list_bg_4.raise_()
        self.label_list_bg_5.raise_()
        self.label_list_bg_2.raise_()
        self.label_list_bg_3.raise_()
        self.label_list_bg_1.raise_()
        self.label_list_bg_0.raise_()
        self.label_userinfo_all_bg.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.label_right_top_time.raise_()
        self.label_right_top_date.raise_()
        self.gridLayoutWidget.raise_()
        self.label_user_list_head_rect_0.raise_()
        self.gridLayoutWidget_2.raise_()
        self.gridLayoutWidget_3.raise_()
        self.gridLayoutWidget_4.raise_()
        self.label_user_list_head_rect_3.raise_()
        self.label_user_list_head_rect_2.raise_()
        self.gridLayoutWidget_5.raise_()
        self.gridLayoutWidget_6.raise_()
        self.gridLayoutWidget_8.raise_()
        self.label_user_list_head_rect_5.raise_()
        self.label_user_list_head_rect_6.raise_()
        self.label_user_list_head_rect_4.raise_()
        self.label_user_list_head_rect_1.raise_()
        self.label_notice.raise_()
        self.user_list_right_wraper.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_userinfo_all_name.setText(_translate("MainWindow", "姓名："))
        self.label_userinfo_all_sex.setText(_translate("MainWindow", "性别："))
        self.label_userinfo_all_age.setText(_translate("MainWindow", "年龄："))
        self.label_userinfo_all_rank.setText(_translate("MainWindow", "职位："))
        self.label_userinfo_all_dept.setText(_translate("MainWindow", "部门："))
        self.label_userinfo_all_slogan.setText(_translate("MainWindow", "签名：工作是我的全部"))
        self.label_right_top_time.setText(_translate("MainWindow", "12:38"))
        self.label_right_top_date.setText(_translate("MainWindow", "[2018-07-11]"))
        self.label_user_list_time_0.setText(_translate("MainWindow", "14:59"))
        self.label_user_list_date_0.setText(_translate("MainWindow", "[2018-07-10]"))
        self.label_user_list_name_0.setText(_translate("MainWindow", "邢珈瑞"))
        self.label_user_list_dept_0.setText(_translate("MainWindow", "信息化部"))
        self.label_user_list_time_1.setText(_translate("MainWindow", "14:59"))
        self.label_user_list_date_1.setText(_translate("MainWindow", "[2018-07-10]"))
        self.label_user_list_name_1.setText(_translate("MainWindow", "邢珈瑞"))
        self.label_user_list_dept_1.setText(_translate("MainWindow", "信息化部"))
        self.label_user_list_time_2.setText(_translate("MainWindow", "14:59"))
        self.label_user_list_date_2.setText(_translate("MainWindow", "[2018-07-10]"))
        self.label_user_list_name_2.setText(_translate("MainWindow", "邢珈瑞"))
        self.label_user_list_dept_2.setText(_translate("MainWindow", "信息化部"))
        self.label_user_list_time_3.setText(_translate("MainWindow", "14:59"))
        self.label_user_list_date_3.setText(_translate("MainWindow", "[2018-07-10]"))
        self.label_user_list_name_3.setText(_translate("MainWindow", "邢珈瑞"))
        self.label_user_list_dept_3.setText(_translate("MainWindow", "信息化部"))
        self.label_user_list_time_5.setText(_translate("MainWindow", "14:59"))
        self.label_user_list_date_5.setText(_translate("MainWindow", "[2018-07-10]"))
        self.label_user_list_name_5.setText(_translate("MainWindow", "邢珈瑞"))
        self.label_user_list_dept_5.setText(_translate("MainWindow", "信息化部"))
        self.label_user_list_time_6.setText(_translate("MainWindow", "14:59"))
        self.label_user_list_date_6.setText(_translate("MainWindow", "[2018-07-10]"))
        self.label_user_list_name_6.setText(_translate("MainWindow", "邢珈瑞"))
        self.label_user_list_dept_6.setText(_translate("MainWindow", "信息化部"))
        self.label_user_list_time_4.setText(_translate("MainWindow", "14:59"))
        self.label_user_list_date_4.setText(_translate("MainWindow", "[2018-07-10]"))
        self.label_user_list_name_4.setText(_translate("MainWindow", "邢珈瑞"))
        self.label_user_list_dept_4.setText(_translate("MainWindow", "信息化部"))
        self.label_notice.setText(_translate("MainWindow", "通知：天气炎热，请做好防暑工作。"))
        self.label_shadow_tips.setText(_translate("MainWindow", "请将面部靠近摄像头唤醒考勤系统"))
        MainWindow.showFullScreen()
        self.setWindowFlags(QtCore.Qt.CustomizeWindowHint)
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

